CREATE DATABASE keycloak OWNER keycloak;
CREATE DATABASE profile OWNER profile;

GRANT CONNECT ON DATABASE keycloak TO keycloak;
GRANT CONNECT ON DATABASE profile TO profile;

\c keycloak
ALTER SCHEMA public OWNER TO keycloak;
GRANT USAGE, CREATE ON SCHEMA public TO keycloak;

ALTER DEFAULT PRIVILEGES FOR ROLE keycloak
IN SCHEMA public
GRANT ALL ON TABLES TO keycloak;

ALTER DEFAULT PRIVILEGES FOR ROLE keycloak
IN SCHEMA public
GRANT ALL ON SEQUENCES TO keycloak;

\c profile
ALTER SCHEMA public OWNER TO profile;
GRANT USAGE, CREATE ON SCHEMA public TO profile;

ALTER DEFAULT PRIVILEGES FOR ROLE profile
IN SCHEMA public
GRANT ALL ON TABLES TO profile;

ALTER DEFAULT PRIVILEGES FOR ROLE profile
IN SCHEMA public
GRANT ALL ON SEQUENCES TO profile;
