// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/tokenissuer.proto

package tokenissuerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TokenValidator_Validate_FullMethodName = "/tokenissuer.TokenValidator/Validate"
)

// TokenValidatorClient is the client API for TokenValidator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenValidatorClient interface {
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type tokenValidatorClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenValidatorClient(cc grpc.ClientConnInterface) TokenValidatorClient {
	return &tokenValidatorClient{cc}
}

func (c *tokenValidatorClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, TokenValidator_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenValidatorServer is the server API for TokenValidator service.
// All implementations must embed UnimplementedTokenValidatorServer
// for forward compatibility.
type TokenValidatorServer interface {
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	mustEmbedUnimplementedTokenValidatorServer()
}

// UnimplementedTokenValidatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenValidatorServer struct{}

func (UnimplementedTokenValidatorServer) Validate(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedTokenValidatorServer) mustEmbedUnimplementedTokenValidatorServer() {}
func (UnimplementedTokenValidatorServer) testEmbeddedByValue()                        {}

// UnsafeTokenValidatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenValidatorServer will
// result in compilation errors.
type UnsafeTokenValidatorServer interface {
	mustEmbedUnimplementedTokenValidatorServer()
}

func RegisterTokenValidatorServer(s grpc.ServiceRegistrar, srv TokenValidatorServer) {
	// If the following call pancis, it indicates UnimplementedTokenValidatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokenValidator_ServiceDesc, srv)
}

func _TokenValidator_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenValidatorServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenValidator_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenValidatorServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenValidator_ServiceDesc is the grpc.ServiceDesc for TokenValidator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenValidator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tokenissuer.TokenValidator",
	HandlerType: (*TokenValidatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _TokenValidator_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tokenissuer.proto",
}
