FROM golang:1.25.6-alpine AS builder

WORKDIR /temp

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go test -c cmd/main_test.go -o e2e

FROM alpine:latest

WORKDIR /root/
COPY --from=builder /temp/e2e .

CMD ["./e2e", "-test.v"]
