// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: tokenissuer.proto

package tokenissuerpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_tokenissuer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tokenissuer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_tokenissuer_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectId     string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_tokenissuer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tokenissuer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_tokenissuer_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateResponse) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

var File_tokenissuer_proto protoreflect.FileDescriptor

const file_tokenissuer_proto_rawDesc = "" +
	"\n" +
	"\x11tokenissuer.proto\x12\vtokenissuer\x1a\x1cgoogle/api/annotations.proto\"4\n" +
	"\x0fValidateRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"1\n" +
	"\x10ValidateResponse\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId2Y\n" +
	"\x0eTokenValidator\x12G\n" +
	"\bValidate\x12\x1c.tokenissuer.ValidateRequest\x1a\x1d.tokenissuer.ValidateResponseB\x14Z\x12./pb/tokenissuerpbb\x06proto3"

var (
	file_tokenissuer_proto_rawDescOnce sync.Once
	file_tokenissuer_proto_rawDescData []byte
)

func file_tokenissuer_proto_rawDescGZIP() []byte {
	file_tokenissuer_proto_rawDescOnce.Do(func() {
		file_tokenissuer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tokenissuer_proto_rawDesc), len(file_tokenissuer_proto_rawDesc)))
	})
	return file_tokenissuer_proto_rawDescData
}

var file_tokenissuer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tokenissuer_proto_goTypes = []any{
	(*ValidateRequest)(nil),  // 0: tokenissuer.ValidateRequest
	(*ValidateResponse)(nil), // 1: tokenissuer.ValidateResponse
}
var file_tokenissuer_proto_depIdxs = []int32{
	0, // 0: tokenissuer.TokenValidator.Validate:input_type -> tokenissuer.ValidateRequest
	1, // 1: tokenissuer.TokenValidator.Validate:output_type -> tokenissuer.ValidateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tokenissuer_proto_init() }
func file_tokenissuer_proto_init() {
	if File_tokenissuer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tokenissuer_proto_rawDesc), len(file_tokenissuer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tokenissuer_proto_goTypes,
		DependencyIndexes: file_tokenissuer_proto_depIdxs,
		MessageInfos:      file_tokenissuer_proto_msgTypes,
	}.Build()
	File_tokenissuer_proto = out.File
	file_tokenissuer_proto_goTypes = nil
	file_tokenissuer_proto_depIdxs = nil
}
