postgres:
  host: localhost
  port: 5430
  user: profile
  password: profile
  db_name: profile
  ssl_mode: disable

s3:
  client:
    region: us-east-1
    endpoint: http://localhost:9000
    access_key_id: profile
    secret_access_key: profile-secret
    path_style: true
  bucket: avatar
  presign_duration: 1m

http: 
  host: 0.0.0.0 
  port: 8080
  debug_mode: true

verify:
  jwks_endpoint: http://localhost:7070/realms/main/protocol/openid-connect/certs

avatar_deleter:
  run_hour_utc: -1
  interval: 10m

profile_deleter:
  kafka:
    brokers:
    - localhost:9092
    topics:
    - keycloak-events
    - keycloak-admin-events
    group_id: profile-deleter
  delay: 10s

migrations_path: file://migrations