FROM golang:1.25.6-alpine AS builder
ARG TARGETARCH
WORKDIR /temp
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH} go build -o app ./cmd/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /temp/app .
CMD ["./app"]